CREATE TABLE SW_MOVIE (
  ID BIGINT NOT NULL,
  TITLE VARCHAR(500) NOT NULL,
  DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;